import type { Metadata } from "next";
import { siteConfig } from "@/config/site";
import { createMetadata } from "@/lib/seo";
import { LegalPage, type LegalSection } from "@/components/layout/LegalPage";

export const metadata: Metadata = createMetadata({
  title: "Privacy Policy",
  description: `How ${siteConfig.name} collects, uses and protects personal information.`,
  path: "/privacy-policy",
});

// TODO: Replace with the privacy policy approved by legal counsel.
const sections: LegalSection[] = [
  {
    heading: "1. Who we are",
    paragraphs: [
      `${siteConfig.legalName} (“ARK”, “we”, “us”) operates this website. Our registered address is ${siteConfig.contact.address.line1}, ${siteConfig.contact.address.city}, ${siteConfig.contact.address.state} ${siteConfig.contact.address.postalCode}, ${siteConfig.contact.address.country}. Questions about this policy can be sent to ${siteConfig.contact.email}.`,
    ],
  },
  {
    heading: "2. Information we collect",
    paragraphs: ["We collect information you provide directly and limited technical information generated by your use of the site."],
    bullets: [
      "Enquiry details: name, company, phone number, email, city, project type and message submitted through our forms.",
      "Newsletter subscription: email address.",
      "Job applications: information you send by email, including your CV.",
      "Technical data: IP address, browser type, pages visited and approximate location, collected through server logs and analytics where enabled.",
    ],
  },
  {
    heading: "3. How we use information",
    paragraphs: ["We use personal information to respond to enquiries, prepare proposals, deliver and support projects, send communications you have requested, recruit for open roles, and operate and secure the website."],
  },
  {
    heading: "4. Legal basis and consent",
    paragraphs: [
      "We process information with your consent, to take steps at your request before entering a contract, to perform a contract, or where we have a legitimate interest such as improving our services and protecting our systems, in accordance with applicable Indian law including the Digital Personal Data Protection Act, 2023.",
    ],
  },
  {
    heading: "5. Sharing",
    paragraphs: [
      "We share information only with service providers who process it on our behalf (for example hosting, email delivery and CRM providers), with dealers or partners where needed to serve your enquiry, and where required by law. We do not sell personal information.",
    ],
  },
  {
    heading: "6. Retention",
    paragraphs: ["We keep enquiry and project data for as long as needed to serve you and meet legal, accounting and warranty obligations, after which it is deleted or anonymised."],
  },
  {
    heading: "7. Your rights",
    paragraphs: [`You may request access to, correction of, or deletion of your personal information, or withdraw consent, by contacting ${siteConfig.contact.email}. We will respond within the timelines required by applicable law.`],
  },
  {
    heading: "8. Cookies and analytics",
    paragraphs: ["The site uses strictly necessary cookies to function. If analytics or marketing cookies are enabled in the future, this section and any consent mechanism will be updated accordingly."],
  },
  {
    heading: "9. Security",
    paragraphs: ["We apply reasonable technical and organisational measures to protect personal information, including encrypted connections and access controls."],
  },
  {
    heading: "10. Changes to this policy",
    paragraphs: ["We may update this policy from time to time. The date at the top of the page reflects the latest revision."],
  },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      description="How we collect, use and protect the information you share with us."
      updated="9 September 2026"
      path="/privacy-policy"
      sections={sections}
    />
  );
}
